<a href="https://colab.research.google.com/github/sahanal2603/Data-Science-and-Analytics/blob/master/Confusion_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
y_actual=['cat','cat','cat','dog','dog','dog','cat','dog','cat']
count_cats=0
count_dogs=0
for animal in y_actual:
    if animal=='cat':
        count_cats=count_cats+1
    if animal == 'dog':
        count_dogs+=1

print('number of dogs =', count_dogs)
print('number of cats = ', count_cats)


number of dogs = 4
number of cats =  5


In [3]:
y_actual=['cat',  'cat',  'cat',  'dog',  'dog',  'dog',  'cat',  'dog',  'cat',  'dog',  'cat']
y_predict=['dog', 'cat',  'cat',  'cat',  'dog',  'dog',  'cat',  'dog',  'cat',  'cat',  'cat']
count_correct_cats=0
count_correct_dogs=0
count_incorrect_cats=0
count_incorrect_dogs=0
N=len(y_actual)
for i in np.arange(N):
    if y_actual[i]==y_predict[i] and y_actual[i]=='cat':
        count_correct_cats+=1
    if y_actual[i]==y_predict[i] and y_actual[i]=='dog':
        count_correct_dogs+=1
    if y_actual[i]!=y_predict[i] and y_actual[i]=='cat':
        count_incorrect_cats+=1
    if y_actual[i]!=y_predict[i] and y_actual[i]=='dog':
        count_incorrect_dogs+=1

print(count_correct_cats)
print(count_correct_dogs)

print(count_incorrect_cats)
print(count_incorrect_dogs)

5
3
1
2


In [4]:
# covid test results

y_actual=['positive','positive','positive','negative','positive','positive','negative','negative',
          'negative','negative','negative','negative','negative']
          
y_predict=['positive','negative','positive','negative','negative','positive','negative','negative',
           'negative','negative','positive','negative','negative']

count_correct_positive=0
count_correct_negative=0
count_incorrect_positive=0
count_incorrect_negative=0
N=len(y_actual)
for i in np.arange(N):
    if y_actual[i]==y_predict[i] and y_actual[i]=='positive':
        count_correct_positive+=1
    if y_actual[i]==y_predict[i] and y_actual[i]=='negative':
        count_correct_negative+=1
    if y_actual[i]!=y_predict[i] and y_actual[i]=='positive':
        count_incorrect_positive+=1
    if y_actual[i]!=y_predict[i] and y_actual[i]=='negative':
        count_incorrect_negative+=1

print(count_correct_positive)
print(count_correct_negative)

print(count_incorrect_positive)
print(count_incorrect_negative)


3
7
2
1


In [5]:
# covid test results

y_actual=['positive','positive','positive','negative',
          'positive','positive','negative','negative',
          'negative','negative','negative','negative']

y_predict=['positive','negative','positive','negative',
           'negative','positive','negative','negative',
           'negative','negative','positive','negative']

true_positive=0     # positive being identified as positive
true_negative=0     # negative being identified as negative
false_positive=0    # negative being identified as positive
false_negative=0    # positive being identified as negative
N=len(y_actual)
for i in np.arange(N):
    if y_actual[i]==y_predict[i] and y_actual[i]=='positive':
        true_positive+=1
    if y_actual[i]==y_predict[i] and y_actual[i]=='negative':
        true_negative+=1
    if y_actual[i]!=y_predict[i] and y_actual[i]=='positive':
        false_negative +=1
    if y_actual[i]!=y_predict[i] and y_actual[i]=='negative':
        false_positive+=1

#conf_matrix=np.zeros(2,2)
conf_matrix=np.zeros((2,2))
conf_matrix[0,0]=true_positive    # also known as hit rate, correct hit 
conf_matrix[0,1]=false_negative   # also known as Type II error, or miss or Over-estimation 
conf_matrix[1,0]=false_positive   # also known as Type I error, or known as False Alarm or Under-estimation
conf_matrix[1,1]=true_negative    # also known as correct rejection

print('Our Confusion Matrix is = \n',conf_matrix)

print('\nDescription of our Confusion Matrix is = \n')
print('                  PREDICTED POSITIVE      PREDICTED NEGATIVE')
print('ACTUAL-POSITIVE:   [True Positive,        False Negative]')
print('ACTUAL- NEGATIVE:  [False Positive,       True Negative]' )


Our Confusion Matrix is = 
 [[3. 2.]
 [1. 6.]]

Description of our Confusion Matrix is = 

                  PREDICTED POSITIVE      PREDICTED NEGATIVE
ACTUAL-POSITIVE:   [True Positive,        False Negative]
ACTUAL- NEGATIVE:  [False Positive,       True Negative]


In [6]:
# Various metrics from confusion matrix
# All diagonal elements are correct predictions
print(conf_matrix)

Accuracy=(conf_matrix[0,0] + conf_matrix[1,1])/(conf_matrix[0,0] + conf_matrix[0,1]+conf_matrix[1,0] + conf_matrix[1,1])
print('\n Accuracy = ', Accuracy)

# True Positive Rate (TPR), OR recall, OR hit rate OR sensitivity
#  TPR = (True Positive )/(Total Actual Positive)    
# TPR= (True Positive)/(True Positive + False Negative )

TPR= conf_matrix[0,0]/(conf_matrix[0,0] + conf_matrix[0,1])
print('\n TPR = Recall = hit rate = Sensistivity =  ', TPR)

# True negative rate (TNR) OR Specificity OR Selectivity 
# TNR = (True Negative)/(Total Actual Negative)
# TNR = (True Negative)/(True Negative + False Positive)
TNR =conf_matrix[1,1]/(conf_matrix[1,0] + conf_matrix[1,1])
print('\n TNR = Specificity = Selectivity = ', TNR)

# precision OR Positive Predictive Value = PPV
# PPV = True Positive / (True Positive + False Positive)
PPV = conf_matrix[0,0]/(conf_matrix[0,0] + conf_matrix[1,0])
print('\n PPV = Precision = ', PPV)

# Balanced Accuracy = (TPR + TNR)/2
balanced_accuracy = (TPR+TNR)/2
print('\n Balanced Accuracy = ', balanced_accuracy)

# F1 score
# F1 = (2*True_Positive)/ (2*True_Positive + False Positive + False Negative )

F1= (2*conf_matrix[0,0])/ (2*conf_matrix[0,0] + conf_matrix[1,0] + conf_matrix[0,1])
print('\n F1 score = ', F1)


[[3. 2.]
 [1. 6.]]

 Accuracy =  0.75

 TPR = Recall = hit rate = Sensistivity =   0.6

 TNR = Specificity = Selectivity =  0.8571428571428571

 PPV = Precision =  0.75

 Balanced Accuracy =  0.7285714285714285

 F1 score =  0.6666666666666666


In [7]:
# Example II
# To compute all parameters, given the Confusion Matrix, Biased Dataset

#conf_matrix=np.zeros(2,2)
conf_matrix=np.zeros((2,2))
conf_matrix[0,0] = 3
conf_matrix[0,1] = 4
conf_matrix[1,0] = 2
conf_matrix[1,1] = 81

print('Our Confusion Matrix is = \n',conf_matrix)

# Various metrics from confusion matrix

Accuracy=(conf_matrix[0,0] + conf_matrix[1,1])/(conf_matrix[0,0] + conf_matrix[0,1]+conf_matrix[1,0] + conf_matrix[1,1])
print('\n Accuracy = ', Accuracy)

# True Positive Rate (TPR), OR recall, OR hit rate OR sensitivity
# TPR= (True Positive)/(True Positive + False Negative )

TPR= conf_matrix[0,0]/(conf_matrix[0,0] + conf_matrix[0,1])
print('\n TPR = Recall = hit rate = Sensistivity =  ', TPR)

# True negative rate (TNR) OR Specificity OR Selectivity 
# TNR = (True Negative)/(Total Actual Negative)
# TNR = (True Negative)/(True Negative + False Positive)
TNR =conf_matrix[1,1]/(conf_matrix[1,0] + conf_matrix[1,1])
print('\n TNR = Specificity = Selectivity = ', TNR)

# precision OR Positive Predictive Value = PPV
# PPV = True Positive / (True Positive + False Positive)
PPV = conf_matrix[0,0]/(conf_matrix[0,0] + conf_matrix[1,0])
print('\n PPV = Precision = ', PPV)

# Balanced Accuracy = (TPR + TNR)/2
balanced_accuracy = (TPR+TNR)/2
print('\n Balanced Accuracy = ', balanced_accuracy)

# F1 score
# F1 = (2*True_Positive)/ (2*True_Positive + False Positive + False Negative )

F1= (2*conf_matrix[0,0])/ (2*conf_matrix[0,0] + conf_matrix[1,0] + conf_matrix[0,1])
print('\n F1 score = ', F1)


Our Confusion Matrix is = 
 [[ 3.  4.]
 [ 2. 81.]]

 Accuracy =  0.9333333333333333

 TPR = Recall = hit rate = Sensistivity =   0.42857142857142855

 TNR = Specificity = Selectivity =  0.9759036144578314

 PPV = Precision =  0.6

 Balanced Accuracy =  0.7022375215146299

 F1 score =  0.5


In [8]:
# Example III
# To compute all parameters, given the Confusion Matrix , Balanced Data set

#conf_matrix=np.zeros(2,2)
conf_matrix=np.zeros((2,2))
conf_matrix[0,0] = 27
conf_matrix[0,1] = 8
conf_matrix[1,0] = 5
conf_matrix[1,1] = 50


print('Our Confusion Matrix is = \n',conf_matrix)

# Various metrics from confusion matrix

Accuracy=(conf_matrix[0,0] + conf_matrix[1,1])/(conf_matrix[0,0] + conf_matrix[0,1]+conf_matrix[1,0] + conf_matrix[1,1])
print('\n Accuracy = ', Accuracy)

# True Positive Rate (TPR), OR recall, OR hit rate OR sensitivity
# TPR= (True Positive)/(True Positive + False Negative )

TPR= conf_matrix[0,0]/(conf_matrix[0,0] + conf_matrix[0,1])
print('\n TPR = Recall = hit rate = Sensistivity =  ', TPR)

# True negative rate (TNR) OR Specificity OR Selectivity 
# TNR = (True Negative)/(Total Actual Negative)
# TNR = (True Negative)/(True Negative + False Positive)
TNR =conf_matrix[1,1]/(conf_matrix[1,0] + conf_matrix[1,1])
print('\n TNR = Specificity = Selectivity = ', TNR)

# precision OR Positive Predictive Value = PPV
# PPV = True Positive / (True Positive + False Positive)
PPV = conf_matrix[0,0]/(conf_matrix[0,0] + conf_matrix[1,0])
print('\n PPV = Precision = ', PPV)

# Balanced Accuracy = (TPR + TNR)/2
balanced_accuracy = (TPR+TNR)/2
print('\n Balanced Accuracy = ', balanced_accuracy)

# F1 score
# F1 = (2*True_Positive)/ (2*True_Positive + False Positive + False Negative )

F1= (2*conf_matrix[0,0])/ (2*conf_matrix[0,0] + conf_matrix[1,0] + conf_matrix[0,1])
print('\n F1 score = ', F1)


Our Confusion Matrix is = 
 [[27.  8.]
 [ 5. 50.]]

 Accuracy =  0.8555555555555555

 TPR = Recall = hit rate = Sensistivity =   0.7714285714285715

 TNR = Specificity = Selectivity =  0.9090909090909091

 PPV = Precision =  0.84375

 Balanced Accuracy =  0.8402597402597403

 F1 score =  0.8059701492537313


In [9]:
from sklearn.metrics import confusion_matrix

y_actual  = np.array([ 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0])
y_predict = np.array([ 1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1])

CNF=confusion_matrix(y_actual,y_predict)
print(CNF)


[[ 5  2]
 [ 3 12]]


In [10]:
from sklearn.metrics import accuracy_score

y_actual  = np.array([ 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0])
y_predict = np.array([ 1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1])

AC=accuracy_score(y_actual,y_predict)
print('Accuracy Score = ', AC)

Accuracy Score =  0.7727272727272727


In [11]:
from sklearn.metrics import f1_score

y_actual  = np.array([ 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0])
y_predict = np.array([ 1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1])

f1_score(y_actual,y_predict)

0.8275862068965518