<a href="https://colab.research.google.com/github/sahanal2603/Data-Science-and-Analytics/blob/master/Practice_Python_Data_Science_ecosystem_Lab_2_%5BNumpy%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This content is taken directly from the Tutorial session of the TEQIP III sponsored Faculty Development program, conducted by IIT Ghandinagar, during 11 to 23 January, 2021

# **Importing NumPy**
We'll start with the standard NumPy import, under the alias *'np'*.

In [ ]:
import numpy as np

# **Creating Arrays from Python Lists**
Use np.array to create arrays from Python lists.

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible.

In [ ]:
#Here, integers are up-cast to floating point:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
#Use the 'dtype' keyword to explicitly set data type of the resulting array:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
x=np.array([range(-3,8,2)])


In [ ]:
#Initializing a multidimensional array using a list of lists:
np.array([range(i, i + 9,2) for i in [1,2,3,4]])

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 3,  5,  7,  9, 11],
       [ 4,  6,  8, 10, 12]])

# **Creating Arrays from Scratch**

In [ ]:
# Create a length-5 integer array filled with zeros
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((4,2),4.5)

array([[4.5, 4.5],
       [4.5, 4.5],
       [4.5, 4.5],
       [4.5, 4.5]])

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np

In [ ]:
np.array([range(0,20,2)]).T

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [ ]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 2, 11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [ ]:
np.random.random((2,4))


array([[0.18204877, 0.65626485, 0.43284298, 0.38863336],
       [0.45963895, 0.16078952, 0.07902717, 0.44467576]])

In [ ]:
np.random.normal((3,2))

array([3.28010507, 1.87982537])

In [ ]:
np.random.randint(10,size=(3,3))

array([[2, 8, 1],
       [3, 4, 9],
       [4, 3, 6]])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.77188451, 0.67557322, 0.93273262],
       [0.79895096, 0.03389078, 0.27714569],
       [0.65549134, 0.40056742, 0.0613307 ]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# **Basics of NumPy Arrays**

## **1. NumPy Array Attributes**
*Determining the size, shape, memory consumption, and data types of arrays*

In [ ]:
#Define three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. 
#We'll use NumPy's random number generator.
#Use 'seed' to ensure that the same random arrays are generated each time this code is run.

np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
#Each array has attributes:
# (1) ndim (the number of dimensions), 
# (2) shape (the size of each dimension), and 
# (3) size (the total size of the array)

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


## **2. NumPy Array Indexing**
*Getting and setting the value of individual array elements*

In [ ]:
#Print x1
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [ ]:
#Access first element from x1 (1D Array)
#This is similar to accessing elements from lists in Python
x3[1,1,1]=108
print(x3)

[[[  8   1   5   9   8]
  [  9   4   3   0   3]
  [  5   0   2   3   8]
  [  1   3   3   3   7]]

 [[  0   1   9   9   0]
  [  4 108   3   2   7]
  [  2   0   0   4   5]
  [  5   6   8   4   1]]

 [[  4   9   8   1   1]
  [  7   9   9   3   6]
  [  7   2   0   3   5]
  [  9   4   4   6 108]]]


In [ ]:
#Access second last element from x1
x1[-2]

7

In [ ]:
#Print x2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
#Access element at first row, fist column in x2 (2D Array)
x2[0, 0]

3

In [ ]:
#Access element at third row, fourth column from reverse in x2 
print("Old value:", x2[2, -4])

#Set value of element at third row, fourth column from reverse in x2 to 11
x2[2, -4] = 11
print("New value:", x2[2, -4])

Old value: 1
New value: 11


## **3. NumPy Array Slicing**
*Getting and setting smaller subarrays within a larger array*

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### **3.1 One-dimensional subarrays**

In [ ]:
np.random.seed(45)
xi=np.random.randint(10,size=7)
print(xi)
xx=xi[::-1]
print(xx)
print(xi+xx)

[3 0 5 3 4 9 8]
[8 9 4 3 5 0 3]
[11  9  9  6  9  9 11]


In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
print(x1[:3])  # first three elements
print(x1[4:])  # elements after index 4
print(x1[1:4])  # middle sub-array
print(x1[::-1])  # all elements, reversed
print(x1[4::-2])  # reversed every other from index 4

[5 0 3]
[7 9]
[0 3 3]
[9 7 3 3 0 5]
[7 3 5]


### **3.2 Multi-dimensional subarrays**

In [ ]:
np.random.seed(45)
x2=np.random.randint(10,size=(3,5))
print(x2)

[[3 0 5 3 4]
 [9 8 1 5 9]
 [6 8 7 8 5]]


In [ ]:
x2[:2, :3]  # two rows, three columns

array([[3, 0, 5],
       [4, 9, 8]])

In [ ]:
x2[:3, ::2]  # all rows, every other column

array([[3, 5, 4],
       [9, 1, 9],
       [6, 7, 5]])

In [ ]:
print(x2[:, 0])  # first column of x2

[3 9 6]


In [ ]:
print(x2[-1, :])  # last row of x2

[6 8 7 8 5]


### **3.3 Creating copies of arrays**

In [ ]:
print(x2)

#Extract a  2×2  subarray from x2
x2_sub = x2[:2, :3]
print("\n", x2_sub)

[[3 0 5 3 4]
 [9 8 1 5 9]
 [6 8 7 8 5]]

 [[3 0 5]
 [9 8 1]]


In [ ]:
#Now if we modify this subarray, we'll see that the original array is changed!
x2_sub[0, 0] = 108
print(x2_sub)
print("\n", x2)

[[108   0   5]
 [  9   8   1]]

 [[108   0   5   3   4]
 [  9   8   1   5   9]
 [  6   8   7   8   5]]


In [ ]:
#To copy the data within an array or a subarray use the copy() method
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

x2_sub_copy[0, 0] = 2072
print("\n", x2_sub_copy)

print("\n", x2)

[[108   0]
 [  9   8]]

 [[2072    0]
 [   9    8]]

 [[108   0   5   3   4]
 [  9   8   1   5   9]
 [  6   8   7   8   5]]


## **4. NumPy Array Reshaping**
*Changing the shape of a given array*

In [ ]:
one_d=np.array(range(0,20,2)).T
print(one_d) 
one_dd=np.arange(0,24,2).reshape(3,4)
print(one_dd)   
two_d=one_d.reshape(2,5)
print(two_d)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [ ]:
grid = np.arange(1, 10)
print(grid)

grid = np.arange(1, 10).reshape((3, 3))
print("\n", grid)

[1 2 3 4 5 6 7 8 9]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1, 2, 3])
print(x)

# row vector via reshape
print("\n", x.reshape((1, 3)))

# column vector via reshape
print("\n", x.reshape((3, 1)))

[1 2 3]

 [[1 2 3]]

 [[1]
 [2]
 [3]]


## **5. NumPy Array Concatenation and Splitting**
*Combining multiple arrays into one, and splitting one array into many*

In [ ]:
#Array concatenation: One-dimensional array

x = np.random.randint(10,size=(2,3))
y = np.random.randint(10,size=(2,3))
z = np.random.randint(10,size=(2,3))
c_horz=np.concatenate([x,y,z],axis=1)
print(c_horz)
ch=np.hstack([x,y,z])   #alternate command
print(ch)
c_vert=np.concatenate([x,y,z],axis=0)  #this is the default
cv=np.vstack([x,y,z])   #alternate method
print(c_vert)
print(cv)
c_vert.shape

[[1 3 7 8 8 2 5 8 7]
 [2 1 3 7 4 5 0 1 2]]
[[1 3 7 8 8 2 5 8 7]
 [2 1 3 7 4 5 0 1 2]]
[[1 3 7]
 [2 1 3]
 [8 8 2]
 [7 4 5]
 [5 8 7]
 [0 1 2]]
[[1 3 7]
 [2 1 3]
 [8 8 2]
 [7 4 5]
 [5 8 7]
 [0 1 2]]


(6, 3)

In [ ]:
#Array concatenation: Two-dimensional array

grid = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [3,2,1],
                 [5,6,7]])

# concatenate along the first axis
print(np.concatenate([grid, grid]))

# concatenate along the second axis (zero-indexed)
print("\n", np.concatenate([grid, grid], axis=1))

[[1 2 3]
 [4 5 6]
 [3 2 1]
 [5 6 7]
 [1 2 3]
 [4 5 6]
 [3 2 1]
 [5 6 7]]

 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [3 2 1 3 2 1]
 [5 6 7 5 6 7]]


In [ ]:
#Array concatenation: Arrays with mixed dimensions

#When working with arrays of mixed dimensions, it can be clearer to use:
# (1) np.vstack (vertical stack) and 
# (2) np.hstack (horizontal stack) functions

x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
print(np.vstack([x, grid]))

# horizontally stack the arrays
y = np.array([[99],
              [99]])
print("\n", np.hstack([grid, y]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]

 [[ 9  8  7 99]
 [ 6  5  4 99]]


In [ ]:
#Splitting of arrays

x = np.arange(0,20,2) #[1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) #Here '3' and '5' are split indices
print(x)
print(x1, x2, x3)

[ 0  2  4  6  8 10 12 14 16 18]
[0 2 4] [6 8] [10 12 14 16 18]


In [ ]:
grid = (np.arange(0,25)*2).reshape((5, 5))
grid

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [ ]:
upper, lower = np.vsplit(grid, [1])
print(upper)
print("\n", lower)

[[0 2 4 6 8]]

 [[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print("\n", right)

[[ 0  2]
 [10 12]
 [20 22]
 [30 32]
 [40 42]]

 [[ 4  6  8]
 [14 16 18]
 [24 26 28]
 [34 36 38]
 [44 46 48]]


# **Computation on NumPy Arrays: Universal Functions (ufuncs)**

In [ ]:
#Set 1: Array Arithmetic

x = np.arange(4)
print("x     =", x)
print("x + 2 =", x + 2)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 2 = [2 3 4 5]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [ ]:
x=np.arange(-3,20,4)
print('x=  {} '.format(x))

yadd=np.add(x, 5)
print('add = {}'.format(yadd))

ysub=np.subtract(x, 5)
print('subtract = {}'.format(ysub))

ymul=np.multiply(x, 2)
print('multiply = {}'.format(ymul))

ypower=np.power(x, 3)
print('power = {}'.format(ypower))

ypower=(x)**3     # alternate method
print('power = {}'.format(ypower))

ydivide=np.divide(x, 3)
print('divide = {}'.format(ydivide))

yintdivide=np.floor_divide(x, 3)    # integral component of the divide
print('divide = {}'.format(yintdivide))

ymod=np.mod(x, 3)    # modulo division, the remainder after dividing
print('divide = {}'.format(ymod))

x=  [-3  1  5  9 13 17] 
add = [ 2  6 10 14 18 22]
subtract = [-8 -4  0  4  8 12]
multiply = [-6  2 10 18 26 34]
power = [ -27    1  125  729 2197 4913]
power = [ -27    1  125  729 2197 4913]
divide = [-1.          0.33333333  1.66666667  3.          4.33333333  5.66666667]
divide = [-1  0  1  3  4  5]
divide = [0 1 2 0 1 2]


The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


In [ ]:
#Set 2: Absolute Value

x = np.array([-2, -1, 0, 1, 2])
print(abs(x))
print(np.absolute(x))
print(np.abs(x))

[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]


In [ ]:
#Set 3: Trigonometric Functions

theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

x = [-1, 0, 1]
print("\nx         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [ ]:
#Set 4: Exponents and Logarithms

x = np.arange(5)
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("2^x   =", np.power(2,x))   #alternate method
print("3^x   =", np.power(3, x))

x = [1, 10, 100, 16, 64, np.exp(2)]
print("\nx        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x     = [0 1 2 3 4]
e^x   = [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
2^x   = [ 1.  2.  4.  8. 16.]
2^x   = [ 1  2  4  8 16]
3^x   = [ 1  3  9 27 81]

x        = [1, 10, 100, 16, 64, 7.38905609893065]
ln(x)    = [0.         2.30258509 4.60517019 2.77258872 4.15888308 2.        ]
log2(x)  = [0.         3.32192809 6.64385619 4.         6.         2.88539008]
log10(x) = [0.         1.         2.         1.20411998 1.80617997 0.86858896]


# **Aggregations: Min, Max, and Everything In Between**

In [ ]:
x = np.arange(1, 25, 3)
print(x)

[ 1  4  7 10 13 16 19 22]


In [ ]:
#Find min, max and sum over 1D array
np.min(x), np.max(x), np.sum(x)

(1, 22, 92)

In [ ]:
#Create a multi-dimensional 3x3 array with values from 1 to 9
M = np.random.randint(10, size=16).reshape((4, 4))
print(M)

[[5 5 7 4]
 [0 6 7 7]
 [6 2 9 2]
 [9 9 6 2]]


In [ ]:
#Find min, max and sum over multidimensional array
np.min(M), np.max(M), np.sum(M)

(0, 9, 86)

In [ ]:
# To find minimum value within each column specify 'axis=0'
print(np.min(M, axis=0))

# To find minimum value within each row specify 'axis=0'
print(np.min(M, axis=1))

[0 2 6 2]
[4 0 2 2]


In [ ]:
#Assume 'heights' to be a NumPy array containing heights in centimeters of 15 individuals
from scipy import stats

heights = np.array(sorted([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183]))

print("Heights:           ", heights)
print("Mean height:       ", np.mean(heights))
print("Standard deviation:", np.std(heights))
print("Minimum height:    ", np.min(heights))
print("Maximum height:    ", np.max(heights))
print("25th percentile:   ", np.percentile(heights, 25))
print("Median:            ", np.median(heights))
print("75th percentile:   ", np.percentile(heights, 75))
print("Variance:            ", np.var(heights))
print("Mode  :            ", stats.mode(heights))


Heights:            [163 168 170 171 173 173 173 175 178 183 183 183 185 189 189]
Mean height:        177.06666666666666
Standard deviation: 7.637335195530499
Minimum height:     163
Maximum height:     189
25th percentile:    172.0
Median:             175.0
75th percentile:    183.0
Variance:             58.328888888888876
Mode  :             ModeResult(mode=array([173]), count=array([3]))
<function all at 0x7f57228fad90>


### Other aggregation functions

NumPy provides many other aggregation functions, but we won't discuss them in detail here.
Additionally, most aggregates have a ``NaN``-safe counterpart that computes the result while ignoring missing values, which are marked by the special IEEE floating-point ``NaN`` value (for a fuller discussion of missing data, see [Handling Missing Data](03.04-Missing-Values.ipynb)).
Some of these ``NaN``-safe functions were not added until NumPy 1.8, so they will not be available in older NumPy versions.

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

We will see these aggregates often throughout the rest of the book.

# **Sorting Arrays**

In [ ]:
#Sort 'heights' array in the above section
heights=np.random.randint(100,180, size=(15))

print(heights)
print(np.sort(heights))

[138 112 114 147 117 140 154 155 172 152 152 132 135 118 134]
[112 114 117 118 132 134 135 138 140 147 152 152 154 155 172]


In [ ]:
#A related function is 'argsort', which instead returns the indices of the sorted elements

i = np.argsort(heights)
print(i)

[ 1  2  4 13 11 14 12  0  5  3  9 10  6  7  8]


In [ ]:
#Sorting along rows or columns

rand = np.random.RandomState(45)
X = rand.randint(0, 10, (4, 6))
print(X)

# sort each column of X
print("\n", np.sort(X, axis=0))

# sort each row of X
print("\n", np.sort(X, axis=1))

[[3 0 5 3 4 9]
 [8 1 5 9 6 8]
 [7 8 5 2 8 1]
 [6 4 8 4 6 4]]

 [[3 0 5 2 4 1]
 [6 1 5 3 6 4]
 [7 4 5 4 6 8]
 [8 8 8 9 8 9]]

 [[0 3 3 4 5 9]
 [1 5 6 8 8 9]
 [1 2 5 7 8 8]
 [4 4 4 6 6 8]]


# **Structured Data: NumPy's Structured Arrays**

Imagine that we have several categories of data on a number of people (say, name, age, and weight), and we'd like to store these values for use in a Python program. It would be possible to store these in three separate arrays.

In [ ]:
name = ['Alice', 'Bob', 'Cathy', 'Doug','mani']
age = [25, 45, 37, 19,55]
weight = [55.0, 85.5, 68.0, 61.5,72.0]

But this is a bit clumsy. There's nothing here that tells us that the three arrays are related; it would be more natural if we could use a single structure to store all of this data. NumPy can handle this through structured arrays, which are arrays with compound data types.

In [ ]:
x = np.zeros(5, dtype=int)
print("x          =", x)

# Use a compound data type for structured arrays
# Here 'U10' translates to "Unicode string of maximum length 10," 
#       'i4' translates to "4-byte (i.e., 32 bit) integer," and 
#       'f8' translates to "8-byte (i.e., 64 bit) float."
data = np.zeros(5, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})

print("data       =", data)
print("data.dtype =", data.dtype)

x          = [0 0 0 0 0]
data       = [('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]
data.dtype = [('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [ ]:
#Fill the empty container array with our list values
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5) ('mani', 55, 72. )]


In [ ]:
# Get all names
print("Names                      :", data['name'])

# Get first row of data
print("First row of data          :", data[0])

# Get the name from the last row
print("Name from last row         :", data[-1]['name'])

# Get names where age is under 30
print("Names where age is under 30:", data[data['weight'] >= 70]['name'])

Names                      : ['Alice' 'Bob' 'Cathy' 'Doug' 'mani']
First row of data          : ('Alice', 25, 55.)
Name from last row         : mani
Names where age is under 30: ['Bob' 'mani']


# **NumPy: Axes and Dimensions**

In [ ]:
#The vector has one axis since it is 1-dimensional. So you can only apply a 
#function across axis-0. Axes are always 0 indexed.

np.sum([1,2,3,4], axis=0)

10

In [ ]:
#Matrix is a 2-dimensional data so it has 2 axes.

#Applying sum function across columns
data = np.array([[1,2,3], [4,5,6]])
print(data)

sum = np.sum(data, axis=0) 
print("\n", sum)

#Applying sum function across rows
sum = np.sum(data, axis=1)
print("\n", sum)

#Providing no axis in the arguments to get the sum of all elements together
sum = np.sum(data)
print("\n", sum)

[[1 2 3]
 [4 5 6]]

 [5 7 9]

 [ 6 15]

 21


In [ ]:
#3-Dimensional data (Concept)
#3D data is a collection of 2D data-points(matrix).

#1. Applying sum function across axis-0 means you are summing all matrices together.
#2. Applying sum function across axis-1 means you are summing all vectors inside each metrics.
#3. Applying sum function across axis-2 means you are summing all scalars inside each Vector.

data = np.array([[[1,1,1],
                  [3,3,3]], 
                 
                 [[2,2,2], 
                  [4,4,4]]])

print(data)

sum = np.sum(data, axis=0) 
print("\n Output of axis=0:\n", sum)

sum = np.sum(data, axis=1) 
print("\n Output of axis=1:\n", sum)

sum = np.sum(data, axis=2) 
print("\n Output of axis=2:\n", sum)

[[[1 1 1]
  [3 3 3]]

 [[2 2 2]
  [4 4 4]]]

 Output of axis=0:
 [[3 3 3]
 [7 7 7]]

 Output of axis=1:
 [[4 4 4]
 [6 6 6]]

 Output of axis=2:
 [[ 3  9]
 [ 6 12]]
